// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type LoginRequest struct {
	Username string `json:"username" validate:"required,min=3,max=20"`
	Password string `json:"password" validate:"required,min=6,max=20"`
}

type LoginResponse struct {
	Token  string `json:"token"`
	UserId int64  `json:"userId"`
}

type QaRequest struct {
	Question string `json:"question"`
	Context  string `json:"context"` // 可选，RAG时传入
}

type QaResponse struct {
	Answer  string `json:"answer"`
	Message string `json:"message"`
}

type RagUploadRequest struct {
	FileName string `json:"fileName"`
	FileData []byte `json:"fileData"`
}

type RagUploadResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type RegisterRequest struct {
	Username string `json:"username" validate:"required,min=3,max=20"`
	Password string `json:"password" validate:"required,min=6,max=20"`
}

type RegisterResponse struct {
	UserName string `json:"username"`
	UserId   int64  `json:"userId"`
}
