// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	"rose/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: registerHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/qa",
				Handler: qaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rag/upload",
				Handler: ragUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/todos",
				Handler: createTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/todos",
				Handler: listTodosHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/todos/:todoId",
				Handler: getTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/todos/:todoId",
				Handler: updateTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/todos/:todoId",
				Handler: deleteTodoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
